Disable `-Werror` on `aarch64-apple-darwin` (#296)
* Disable `-Werror` on `aarch64-apple-darwin`

The new `clang` interacts badly with LLVM headers, giving the fatal
error message:

```
/Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-P2C257CXGN.0/build/default-honeycrisp-P2C257CXGN-0/julialang/julia-master/usr/include/llvm/ADT/DenseMap.h:129:16: error: variable 'NumEntries' set but not used [-Werror,-Wunused-but-set-variable]
      unsigned NumEntries = getNumEntries();
               ^
```

Example: https://buildkite.com/julialang/julia-master/builds/23068#0187a57a-fa1f-45ca-8811-a0637827e3da/438-895

We would ideally like to just pass -Wno-unused-but-set-variable` but our makefile variable setting scripts are not sophisticated enough to allow spaces in these values. :(