coverage: protect against missing bk env vars on windows docker (#476)
Hoping to fix this on the Windows coverage job
https://buildkite.com/julialang/julia-master-scheduled/builds/1253#0198f4d8-0062-4789-a57f-6c6cc7e2ffca/19174-19654

```
  | [ Info: base\weakkeydict.jl                                                     95 %            121            127
  | [ Info: Total: 72% (58105/79875)
ERROR: LoadError: KeyError: key "BUILDKITE_BUILD_AUTHOR" not found
  | Stacktrace:
  | [1] (::Base.var"#getindex##11#getindex##12")(k::String)
  | @ Base .\env.jl:164
  | [2] access_env(onError::Base.var"#getindex##11#getindex##12", str::String)
  | @ Base .\env.jl:31
  | [3] getindex
  | @ .\env.jl:164 [inlined]
  | [4] buildkite_env(name_1::String, name_2::String, default::String)
  | @ Main C:\workdir\.buildkite\pipelines\scheduled\coverage\upload_coverage.jl:86
  | [5] setup_buildkite_env()
  | @ Main C:\workdir\.buildkite\pipelines\scheduled\coverage\upload_coverage.jl:242
  | [6] upload_coverage(fcs::Vector{CoverageTools.FileCoverage})
  | @ Main C:\workdir\.buildkite\pipelines\scheduled\coverage\upload_coverage.jl:258
  | [7] top-level scope
  | @ C:\workdir\.buildkite\pipelines\scheduled\coverage\upload_coverage.jl:320
  | [8] include(mod::Module, _path::String)
  | @ Base .\Base.jl:308
  | [9] exec_options(opts::Base.JLOptions)
  | @ Base .\client.jl:330
  | [10] _start()
  | @ Base .\client.jl:563
  | in expression starting at C:\workdir\.buildkite\pipelines\scheduled\coverage\upload_coverage.jl:320
  | 🚨 Error: The command exited with status 1
```

The assumption being docker isn't forwarding the env var because its
empty or not set??